export const featuredStats = [
  { label: "Clubs Tracked", value: "1,248" },
  { label: "Players Indexed", value: "18,932" },
  { label: "Matches Logged", value: "42,610" },
  { label: "Live Updates", value: "Soon" },
];

export const features = [
  {
    eyebrow: "Form",
    statLabel: "Form",
    title: "Club Form Tracking",
    description:
      "Read recent runs, win rate swings, and scoring pace before your next match-up.",
  },
  {
    eyebrow: "Squad",
    statLabel: "Player",
    title: "Player Output",
    description:
      "Break down goals, assists, ratings, and contributions across the full XI.",
  },
  {
    eyebrow: "Matches",
    statLabel: "Games",
    title: "Match History",
    description:
      "Review recent results, scorelines, and momentum without leaving the club page.",
  },
  {
    eyebrow: "Ranks",
    statLabel: "Live Updates",
    title: "Leaderboard Movement",
    description:
      "Spot ranking changes fast and see which clubs are climbing or dropping.",
  },
  {
    eyebrow: "Compare",
    statLabel: "Club",
    title: "Compare Clubs",
    description:
      "Stack two clubs side by side for skill rating, record, goals, and form trends.",
  },
];

export const mockClub = {
  id: "3456623",
  name: "Elite XI",
  platform: "Gen 5",
  record: {
    wins: 88,
    draws: 12,
    losses: 20,
  },
  skillRating: 1820,
  division: "Division 1",
  goalsFor: 312,
  goalsAgainst: 118,
  cleanSheets: 34,
  recentForm: ["W", "W", "D", "L", "W"],
  squad: [
    {
      id: "1",
      name: "Arya",
      position: "ST",
      matches: 120,
      goals: 146,
      assists: 52,
      rating: 8.7,
    },
    {
      id: "2",
      name: "Safwan",
      position: "CAM",
      matches: 115,
      goals: 64,
      assists: 91,
      rating: 8.5,
    },
    {
      id: "3",
      name: "Lockdown",
      position: "CB",
      matches: 108,
      goals: 6,
      assists: 14,
      rating: 7.9,
    },
    {
      id: "4",
      name: "Wall",
      position: "GK",
      matches: 96,
      goals: 0,
      assists: 2,
      rating: 8.1,
    },
  ],
};

export type LeaderboardPlatform = "Gen5" | "Old Gen" | "Switch";
export type LeaderboardRegion = "Worldwide" | "NA" | "EU";

export type TopPlayer = {
  id: string;
  clubId?: string;
  rank: number;
  name: string;
  club: string;
  position: string;
  platform: LeaderboardPlatform;
  region: LeaderboardRegion;
  games: number;
  goals: number;
  assists: number;
  rating: number;
  winRate: number;
  redCards: number;
};

export type TopClub = {
  id: string;
  rank: number;
  name: string;
  division: string;
  platform: LeaderboardPlatform;
  region: LeaderboardRegion;
  games: number;
  wins: number;
  draws: number;
  losses: number;
  goalsFor: number;
  goalsAgainst: number;
  skillRating: number;
};

export const topPlayers: TopPlayer[] = [
  {
    id: "1",
    rank: 1,
    name: "Arya",
    club: "Elite XI",
    position: "ST",
    platform: "Gen5",
    region: "NA",
    games: 126,
    goals: 158,
    assists: 54,
    rating: 8.9,
    winRate: 78,
    redCards: 1,
  },
  {
    id: "2",
    rank: 2,
    name: "Safwan",
    club: "Elite XI",
    position: "CAM",
    platform: "Gen5",
    region: "NA",
    games: 121,
    goals: 69,
    assists: 96,
    rating: 8.7,
    winRate: 76,
    redCards: 0,
  },
  {
    id: "3",
    rank: 3,
    name: "Lockdown",
    club: "Elite XI",
    position: "CB",
    platform: "Gen5",
    region: "NA",
    games: 113,
    goals: 8,
    assists: 17,
    rating: 8.4,
    winRate: 75,
    redCards: 2,
  },
  {
    id: "7",
    rank: 4,
    name: "Mati",
    club: "North London FC",
    position: "LW",
    platform: "Gen5",
    region: "EU",
    games: 118,
    goals: 104,
    assists: 61,
    rating: 8.5,
    winRate: 72,
    redCards: 1,
  },
  {
    id: "8",
    rank: 5,
    name: "Jules",
    club: "Final Third FC",
    position: "CM",
    platform: "Gen5",
    region: "EU",
    games: 109,
    goals: 41,
    assists: 84,
    rating: 8.3,
    winRate: 70,
    redCards: 0,
  },
  {
    id: "9",
    rank: 6,
    name: "Reece",
    club: "North London FC",
    position: "RB",
    platform: "Gen5",
    region: "EU",
    games: 104,
    goals: 12,
    assists: 46,
    rating: 8.1,
    winRate: 69,
    redCards: 3,
  },
  {
    id: "10",
    rank: 7,
    name: "Nico",
    club: "Blue Lock United",
    position: "RW",
    platform: "Old Gen",
    region: "NA",
    games: 97,
    goals: 88,
    assists: 42,
    rating: 8.2,
    winRate: 67,
    redCards: 1,
  },
  {
    id: "11",
    rank: 8,
    name: "Kaiser",
    club: "Munich Saints",
    position: "ST",
    platform: "Gen5",
    region: "EU",
    games: 102,
    goals: 112,
    assists: 24,
    rating: 8.0,
    winRate: 66,
    redCards: 2,
  },
  {
    id: "12",
    rank: 9,
    name: "Tempo",
    club: "East Coast XI",
    position: "CDM",
    platform: "Old Gen",
    region: "NA",
    games: 94,
    goals: 19,
    assists: 53,
    rating: 7.9,
    winRate: 64,
    redCards: 4,
  },
  {
    id: "13",
    rank: 10,
    name: "Ghost",
    club: "Final Third FC",
    position: "GK",
    platform: "Gen5",
    region: "Worldwide",
    games: 91,
    goals: 0,
    assists: 3,
    rating: 7.8,
    winRate: 63,
    redCards: 0,
  },
];

export const topClubs: TopClub[] = [
  {
    id: "3456623",
    rank: 1,
    name: "Elite XI",
    division: "Division 1",
    platform: "Gen5",
    region: "NA",
    games: 134,
    wins: 98,
    draws: 17,
    losses: 19,
    goalsFor: 342,
    goalsAgainst: 126,
    skillRating: 1868,
  },
  {
    id: "2104421",
    rank: 2,
    name: "North London FC",
    division: "Division 1",
    platform: "Gen5",
    region: "EU",
    games: 128,
    wins: 91,
    draws: 15,
    losses: 22,
    goalsFor: 304,
    goalsAgainst: 139,
    skillRating: 1816,
  },
  {
    id: "9087344",
    rank: 3,
    name: "Final Third FC",
    division: "Division 1",
    platform: "Gen5",
    region: "EU",
    games: 121,
    wins: 84,
    draws: 18,
    losses: 19,
    goalsFor: 286,
    goalsAgainst: 121,
    skillRating: 1789,
  },
  {
    id: "8841029",
    rank: 4,
    name: "Blue Lock United",
    division: "Division 1",
    platform: "Old Gen",
    region: "NA",
    games: 116,
    wins: 78,
    draws: 16,
    losses: 22,
    goalsFor: 271,
    goalsAgainst: 148,
    skillRating: 1712,
  },
  {
    id: "5018827",
    rank: 5,
    name: "Munich Saints",
    division: "Division 2",
    platform: "Gen5",
    region: "EU",
    games: 109,
    wins: 72,
    draws: 14,
    losses: 23,
    goalsFor: 249,
    goalsAgainst: 132,
    skillRating: 1664,
  },
  {
    id: "7763401",
    rank: 6,
    name: "East Coast XI",
    division: "Division 2",
    platform: "Old Gen",
    region: "NA",
    games: 104,
    wins: 67,
    draws: 18,
    losses: 19,
    goalsFor: 231,
    goalsAgainst: 128,
    skillRating: 1628,
  },
  {
    id: "4402981",
    rank: 7,
    name: "Redline Rovers",
    division: "Division 2",
    platform: "Gen5",
    region: "Worldwide",
    games: 101,
    wins: 63,
    draws: 15,
    losses: 23,
    goalsFor: 218,
    goalsAgainst: 145,
    skillRating: 1587,
  },
  {
    id: "6519032",
    rank: 8,
    name: "Capital City",
    division: "Division 3",
    platform: "Old Gen",
    region: "EU",
    games: 98,
    wins: 58,
    draws: 17,
    losses: 23,
    goalsFor: 203,
    goalsAgainst: 142,
    skillRating: 1524,
  },
  {
    id: "7650184",
    rank: 9,
    name: "The Press",
    division: "Division 3",
    platform: "Gen5",
    region: "NA",
    games: 96,
    wins: 55,
    draws: 19,
    losses: 22,
    goalsFor: 196,
    goalsAgainst: 136,
    skillRating: 1498,
  },
  {
    id: "3307105",
    rank: 10,
    name: "Apex Albion",
    division: "Division 3",
    platform: "Gen5",
    region: "Worldwide",
    games: 92,
    wins: 52,
    draws: 16,
    losses: 24,
    goalsFor: 184,
    goalsAgainst: 141,
    skillRating: 1456,
  },
];
