ALTER TABLE "Club" ADD COLUMN "badgeUrl" TEXT;

ALTER TABLE "Player" ADD COLUMN "height" TEXT;
ALTER TABLE "Player" ADD COLUMN "nationality" TEXT;
ALTER TABLE "Player" ADD COLUMN "overall" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Player" ADD COLUMN "shots" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "shotSuccessRate" DOUBLE PRECISION;
ALTER TABLE "Player" ADD COLUMN "saves" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "saveSuccessRate" DOUBLE PRECISION;
ALTER TABLE "Player" ADD COLUMN "goalsAgainst" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "cleanSheets" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "passesMade" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "passAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "passAccuracy" DOUBLE PRECISION;
ALTER TABLE "Player" ADD COLUMN "manOfTheMatch" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "manOfTheMatchRate" DOUBLE PRECISION;

CREATE INDEX "Player_nationality_idx" ON "Player"("nationality");
CREATE INDEX "Player_overall_idx" ON "Player"("overall");
